// Correção de tamanho por monstro — os WebP baixados do TibiaWiki (ver
// infrastructure/tibiaSprites.js) têm canvas de tamanhos diferentes (32/64px)
// E, dentro do canvas, a criatura ocupa uma fração variável dele (ratio de
// preenchimento vai de ~0.31 a ~1.07 na amostra real) — sobra de espaço do
// quadro de animação de caminhada, não do tamanho real do bicho. Com
// object-fit:contain puro isso faz o MESMO box (52px na cena, 34px na Battle
// List) renderizar criaturas com tamanho visual bem diferente entre si.
//
// Cada valor aqui é um multiplicador aplicado por CIMA do contain (via
// transform:scale no <img>, dentro de um clip de tamanho fixo — ver
// ui/huntPanel.js: monsterSpriteImg e style.css: .monster-sprite-clip/
// .battle-list-icon) pra normalizar o quanto a criatura preenche a caixa,
// mirando ~88% de preenchimento pra todo mundo. O teto de 1.3x é de
// PROPÓSITO bem mais conservador que o cálculo bruto pediria pros casos mais
// extremos (Bat/Rat chegavam a pedir 2.2x/1.94x) — acima disso a imagem
// amplificada estoura o clip do container e a criatura aparece cortada nas
// bordas em vez de só "maior". Prefere um bicho um pouco menor que o alvo a
// um bicho visualmente quebrado. Gerado uma vez analisando o bounding-box
// alfa (pixels não-transparentes) de cada sprite; só bicho que desviava >=6%
// do padrão entrou na tabela — ausente aqui = já estava correto (escala 1).
// Reprocessar se os sprites mudarem (MONSTER_SPRITE_VER bump em tibiaSprites.js).
export const MONSTER_SPRITE_SCALE = {
  amazon: 1.3,
  bandit: 1.3,
  banshee: 0.88,
  bat: 1.3,
  bear: 1.13,
  behemoth: 0.94,
  black_knight: 1.3,
  bonebeast: 0.92,
  braindeath: 0.88,
  bug: 1.3,
  carrion_worm: 1.3,
  centipede: 1.22,
  cobra: 1.3,
  crocodile: 0.94,
  crypt_defiler: 1.3,
  crypt_shambler: 0.88,
  crystal_spider: 1.15,
  crystal_wolf: 1.13,
  cyclops: 0.89,
  cyclops_drone: 0.91,
  cyclops_smith: 0.92,
  demon: 0.89,
  diblis: 1.22,
  dragon: 0.88,
  dragon_lord: 0.88,
  draken_abomination: 0.88,
  draken_warmaster: 0.88,
  draptor: 1.08,
  dworc: 1.3,
  efreet: 0.91,
  elf: 0.88,
  executioner: 0.88,
  falcon_knight: 1.3,
  ferumbras: 0.92,
  ferumbras_mortal_shell: 0.92,
  feversleep: 0.82,
  frost_dragon: 0.89,
  frost_troll: 1.3,
  fury: 1.3,
  ghastly_dragon: 0.92,
  ghost: 1.3,
  ghoul: 1.3,
  giant_spider: 0.92,
  goblin: 1.3,
  hellfire_fighter: 0.88,
  hellhound: 0.89,
  hero: 0.88,
  hydra: 0.92,
  ice_golem: 0.89,
  juggernaut: 0.88,
  juvenile_cyclops: 0.89,
  kongra: 1.17,
  latrivan: 0.88,
  lich: 1.06,
  lothlorien: 1.3,
  madareth: 0.88,
  massive_water_elemental: 0.88,
  medusa: 1.06,
  merlkin: 1.25,
  minotaur: 0.91,
  minotaur_archer: 1.3,
  minotaur_guard: 0.91,
  minotaur_mage: 1.3,
  morgul: 1.2,
  mummy: 1.3,
  mutated_human: 1.3,
  nightmare: 1.28,
  nightmare_scion: 0.88,
  nzoth: 0.91,
  omruc: 1.1,
  orc: 0.88,
  orc_rider: 0.91,
  orc_shaman: 0.88,
  poacher: 1.3,
  poison_spider: 1.3,
  priestess: 0.91,
  quara_hydromancer: 0.91,
  quara_pincher: 1.13,
  rat: 1.3,
  retching_horror: 0.91,
  rotworm: 1.3,
  scarab: 1.3,
  scorpion: 0.91,
  shulgrax: 0.94,
  sibang: 1.3,
  skeleton: 1.3,
  slime: 1.3,
  snake: 0.88,
  soul_despoiler: 0.94,
  spider: 1.17,
  stalker: 1.3,
  tanjis: 0.88,
  tarantula: 1.2,
  terramite: 1.17,
  troll: 1.3,
  undead_dragon: 0.91,
  ushuriel: 0.88,
  valkyrie: 1.3,
  vampire: 1.3,
  vexclaw: 0.92,
  war_golem: 0.89,
  warlock: 1.3,
  wasp: 1.13,
  werelion: 1.25,
  werewolf: 1.17,
  wolf: 1.13,
  wyvern: 1.3,
  yeti: 0.91,
  zamulosh: 0.89,
  zorvorax: 0.91,
  zulazza: 0.88,
};

export function monsterSpriteScale(monsterId) {
  return MONSTER_SPRITE_SCALE[monsterId] || 1;
}
